### ISSUE TITLE
是否可以增加代理选项

### ISSUE THREAD

**Issue by xfl888** [zwjjiaozhu/jz-translator#4]
是否可以增加代理选项 软件里没有代理设置，导致无法返回数据。比如用bing，让其翻译任意英文，返回：
request error! code=, t: 1679933085.9937475

**Comment by zwjjiaozhu** [comment]
收到，软件默认的调用本地代理的。暂不清楚问题所在，后面我会加一个代理选项

**Comment by zwjjiaozhu** [comment]
V2.3.6支持设置网络代理了
